#
# Custom configuration variables
#
uranus:
  fds:
    host: dev-rhel.cscn.net

# Active MQ
spring:
  activemq:
    broker-url: tcp://${uranus.fds.host}:61616
    user: admin
    password: admin
    in-memory: false
    pool:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${uranus.fds.host}:3306/uranus_fds?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Mf#llsy78g

